### ISSUE TITLE
Could you please give the names of tasks shown in the video?

### ISSUE THREAD

**Issue by shikejianalan** [orbit-surgical/orbit-surgical#1]
Dear Developers, congrats to the great work, it looks very impressive! However, I could not find tasks such as **Shunt Insertion** or **Needle Ring** in the given task list. Could you please confirm that they are not published yet or I am looking at the wrong position?

Bests,
Kejian

**Comment by masoudmoghani** [comment]
Hi Kejian,

Thanks for your interest in our project. Tasks involving soft material will be released in the near future.

Best,
Masoud

**Comment by shikejianalan** [comment]
Thanks for your reply, I'm looking forward to it.
