### ISSUE TITLE
[Question] How to know if a demonstration is completed?

### ISSUE THREAD

**Issue by saprrow** [orbit-surgical/orbit-surgical#2]
Hi, thanks for you great work! 
Although detailed instructions are provided in teleoperation for imitation learning. I don't how to check if a demonstration is completeed and how to save the demontrations.
I appreciate it if you could help me.

Best regrads, 
Jarvi

**Comment by cgchrfchscyrh** [comment]
Hello, I would like to ask if you know how to save the demonstration data using collect_demonstrations.py. It supposes to collect 10 rounds of demo data. But I do not know how to proceed to next round after collecting current round of data, in IsaacSim.
