### ISSUE TITLE
Error in the RL training

### ISSUE THREAD

**Issue by zahir-w** [orbit-surgical/orbit-surgical#3]
Hi, I am interested in your wonderful work. 
When I follow the readme to train the agent with RSL-RL on `Isaac-Reach-PSM-v0`, I get some errors.
I am confused on how to solve the problem.

```error
File "/home/zahir/Code/orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/assets/articulation/articulation.py", line 147, in root_physx_view
    return self._root_physx_view
AttributeError: 'Articulation' object has no attribute '_root_physx_view'. Did you mean: 'root_physx_view'?

```
---
**My devie Info**
- Ubuntu 22.04
- Issac Sim 2023.1.1
- CPU: R9-7945HX
- GPU: RTX 4060
- NVIDIA Driver: 535.171.04
---
Thanks!
Zahir Wang

**Comment by masoudmoghani** [comment]
Hi Zahir,

Thanks for your interest in this project. Please make sure to clone the repo via https. I hope this helps.

Best,
Masoud

**Comment by masoudmoghani** [comment]
Hi @lofrienger,

Same issue was resolved for a colleague of mine by cloning via https as it seemed the repo was not properly cloned with ssh. It might be due to size of some of the assets. Could you please let me know the file size of the repo on your local machine? mine is +100 MB.

Best,
Masoud

**Comment by zahir-w** [comment]
> Hi @zahir-w Could you please share the solution if you have fixed the issue? Thanks a lot!

Hi, @lofrienger. I am sorry that I haven't solved the problem. 
I tried to git the repo by https. 
But it still didn't work for me. 
Maybe I need to try again? 

Best Regards,
Zahir Wang

**Comment by masoudmoghani** [comment]
Hi @lofrienger and @zahir-w 

I just added an instruction to install Git Large File Storage (LFS) to be able to properly get the large files in the repo. I advise installing Git LFS first and then doing a fresh clone to install the repo.

Best,
Masoud

**Comment by zahir-w** [comment]
Hi, @lofrienger @masoudmoghani .
Thanks for your kind help.

Just by clone with 
`git lfs clone https://xxx`
The problem has been is solved. 

Best Regards,
Zahir Wang
