### ISSUE TITLE
link is not available

### ISSUE THREAD

**Issue by yisenhuang** [orbit-surgical/orbit-surgical#6]
The link of [installation guide](https://isaac-orbit.github.io/orbit/source/setup/installation.html) and [Orbit](https://isaac-orbit.github.io/orbit/) are not available now. Could you please provide new links?

Thanks a lot!

**Comment by yisenhuang** [comment]
Dear Masoud,

Thank you very much for your prompt reply!

Your work has garnered significant attention in our laboratory. However, I have encountered some issues during installation, such as function name mismatches. I am pleased to hear that you plan to update your code.

By the way, our Isaac Lab is based on Isaac Sim 4.0.0. Will you also be updating your dependencies? Despite revising all the function names, I continue to experience problems.

The specific issues are listed below:

2024-06-17 14:53:56 [14,454ms] [Warning] [omni.usd] Warning: in _ReportErrors at line 2890 of /buildAgent/work/ac88d7d902b57417/USD/pxr/usd/usd/stage.cpp -- In </World/envs/env_0/Table>: **Could not open asset** @/home/admin3090/OrSur-RLR/source/extensions/orbit.surgical.assets/data/Props/ORBIT_Surgical/Table/table.usd@ for reference introduced by @anon:0x17ac62e0:World0.usd@</World/envs/env_0/Table>. (recomposing stage on stage @anon:0x17ac62e0:World0.usd@ <0x15828260>)

File "/home/admin3090/Is-RLR/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/articulation/articulation.py", line 792, in _initialize_impl
    raise RuntimeError(
**RuntimeError: Failed to find an articulation when resolving '/World/envs/env_.*/Robot'.** Please ensure that the prim has 'USD ArticulationRootAPI' applied.

File "/home/admin3090/Is-RLR/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/articulation/articulation.py", line 146, in root_physx_view
    return self._root_physx_view
AttributeError: 'Articulation' object has no attribute '_root_physx_view'. Did you mean: 'root_physx_view'?

It appears that other researchers have encountered similar problems, as mentioned in [this GitHub issue](https://github.com/orbit-surgical/orbit-surgical/issues/3#issue-2324913676).

Thank you very much for your kind assistance!

Best regards,
Yisen

**Comment by masoudmoghani** [comment]
Hi @yisenhuang 

Thank you for your kind words. I'm excited to hear that!

Yes, all dependencies will be updated soon. I just added an instruction to install Git Large File Storage (LFS) to be able to properly get the large files in the repo. I advise installing Git LFS first and then doing a fresh clone to install the repo.

Best,
Masoud

**Comment by yisenhuang** [comment]
Dear @masoudmoghani,

Thank you so much for your kind assistance!

The problem was fixed after I installed the Git LFS package. I also revised all function names and class names in my repository, which you can find [here](https://github.com/yisenhuang/OrSur-RLR.git).

I successfully ran this repository with IsaacSim 4.0.0 and IsaacLab.

I tested the following commands:

```python
${ORBIT_PATH}/isaaclab.sh -p source/standalone/environments/random_agent.py --task Isaac-Reach-PSM-v0 --num_envs 32
${ORBIT_PATH}/isaaclab.sh -p source/standalone/environments/zero_agent.py --task Isaac-Reach-PSM-v0 --num_envs 32
${ORBIT_PATH}/isaaclab.sh -p source/standalone/environments/list_envs.py
``` 
These commands successfully operated with the revised repository.

I hope this reduces your workload.

Best regards,
Yisen
